# Docker Compose file for local development environment

---
version: "3.8"
services:
  t2v-transformers:
    env_file:
    - 'env.docker'
    build:
      args:
        - 'T2V_TRANSFORMERS_MODEL_NAME=${T2V_TRANSFORMERS_MODEL_NAME:-intfloat/multilingual-e5-small}'
      context: './t2v-transformers'
      dockerfile: 'Dockerfile'
    platform: 'linux/amd64'
    environment:
      ENABLE_CUDA: 0

  weaviate:
    env_file:
    - 'env.docker'
    command:
    - '--host'
    - '0.0.0.0'
    - '--port'
    - '8080'
    - '--scheme'
    - 'http'
    depends_on:
      - t2v-transformers
    image: 'semitechnologies/weaviate:1.23.3'
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      AUTOSCHEMA_ENABLED: 'false'
      CLUSTER_HOSTNAME: 'embedding1'

volumes:
  weaviate_data: